<%@ page contentType="text/html; charset=UTF-8" %><%@ taglib prefix="c" uri="jakarta.tags.core" %>
<section class="container section narrow"><a class="back-link" href="<c:url value='/admin/products'/>">← Quản lý sản phẩm</a><h1>${empty product.id ? 'Thêm cuốn sách mới' : 'Chỉnh sửa sách'}</h1>
<form class="panel edit-form" method="post" enctype="multipart/form-data" action="<c:url value='/admin/product/save'/>">
<input type="hidden" name="_csrf" value="<c:out value='${csrf}'/>"><input type="hidden" name="id" value="<c:out value='${product.id}'/>">
<label for="title">Tên sách</label><input id="title" name="title" class="form-control" required maxlength="200" value="<c:out value='${product.title}'/>">
<label for="author">Tác giả</label><input id="author" name="author" class="form-control" required maxlength="150" value="<c:out value='${product.author}'/>">
<label for="categoryId">Danh mục</label><select id="categoryId" name="categoryId" class="form-select" required><option value="">Chọn danh mục</option><c:forEach items="${categories}" var="category"><option value="${category.id}" ${selectedCategoryId == category.id ? 'selected' : ''}><c:out value="${category.name}"/></option></c:forEach></select>
<div class="row"><div class="col-sm-6"><label for="price">Giá bán (VNĐ)</label><input id="price" name="price" class="form-control" type="number" min="0" max="9999999999.99" step="0.01" required value="<c:out value='${product.price}'/>"></div><div class="col-sm-6"><label for="stock">Số lượng tồn</label><input id="stock" name="stock" class="form-control" type="number" min="0" step="1" required value="<c:out value='${product.stock}'/>"></div></div>
<label for="description">Mô tả</label><textarea id="description" name="description" class="form-control" rows="5" maxlength="10000"><c:out value="${product.description}"/></textarea>
<label for="image">URL ảnh hoặc đường dẫn ảnh hiện tại</label><input id="image" name="image" class="form-control" maxlength="1000" value="<c:out value='${product.image}'/>">
<label for="upload">Hoặc tải ảnh bìa mới</label><input id="upload" name="upload" class="form-control" type="file" accept="image/jpeg,image/png,image/webp"><p class="form-note">JPEG, PNG, WebP · Tối đa 5 MB / 20 megapixel.</p><button class="btn btn-forest">Lưu sách</button></form></section>
