-- REVIEW AND EXECUTE MANUALLY ONLY.
-- Use only for a database that already has the Bài 03 schema.
BEGIN;
ALTER TABLE users ADD COLUMN full_name VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN phone VARCHAR(13) NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN image VARCHAR(1000) NOT NULL DEFAULT '';
COMMIT;
